# Sudo is required due to <https://github.com/travis-ci/travis-ci/issues/8836>
sudo: required
language: node_js
node_js:
  - "8"

addons:
  chrome: stable

install:
  - npm install -g z-schema
  - npm install

script:
  - z-schema data.schema.json data.json
  - python2.7 -m SimpleHTTPServer &
  - npm test
